### ISSUE TITLE
Site suspended

### ISSUE THREAD

**Issue by tomauty** [AngelJumbo/gruvbox-wallpapers#7]
Hi~ I love your wallpaper collection. Looks like the website version has been suspended for some reason? 

<img width="324" alt="image" src="https://user-images.githubusercontent.com/1112872/234586380-4d63fada-cc78-471a-a366-d3d144fadd32.png">

**Comment by AngelJumbo** [comment]
Hi, I just notice an email from render.com, aparently the site got too big and It exceeded the montly traffic for a free account. The site will be back in a few days but, I will search another way to deploy the site I can't pay the fees of render.com.

**Comment by AngelJumbo** [comment]
new site: https://gruvbox-wallpapers.pages.dev/
